### PR TITLE
Migrate to null-safety

### LINKED ISSUE #29: null-safety support

### PR DESCRIPTION
**Pull request by Czappi**
- may throws error
- fixes #29

### CODE REVIEW

**Comment by Czappi** [comment]
errors occurred on build
### **Not safe for merge right now**

**Comment by bitsdojo** [comment]
Hi there! Just added null safety support.

**Comment by Czappi** [comment]
I just finished it too, but it doesn't matter anymore. :D

**Comment by bitsdojo** [comment]
It matters to me that you wanted to help with this! ❤️

**Pull request closed without merging**
