### PR TITLE
migrate to Dart 3

### PR DESCRIPTION
**Pull request by vik-borisov**
- migrate to dart 3
- upgraded dependencies

### CODE REVIEW

**Comment by JHenneberg** [comment]
Great PR. Maybe bumb `5.0.0` to `5.0.5` ?

**Review by Juliotati — COMMENTED** [review]
LGTM!! 🥳

**Comment by cjlapao** [comment]
@Juliotati Could this please be merged?

**Comment by Juliotati** [comment]
@cjlapao 

I would if I could, but I'm not a maintainer of this package. 
However you can update the dependencies locally by overriding them in your `pubspec.yaml`

> add above `dev_dependencies`

```yaml
dependency_overrides:
  google_fonts: ^5.1.0
  intl: ^0.18.1

```

If there's any other dependency that requires to be updated due to conflict just include it in the `dependency_overrides`

**Comment by cjlapao** [comment]
@Juliotati amazing. Let me try this. This is a great project but it seems a bit dead

**Pull request closed without merging**
