### PR TITLE
fix: [WINDOWS] BDW_CUSTOM_FRAME ERROR : Error waiting for a debug connection

### PR DESCRIPTION
**Pull request by bufan22**
fix issues #123 #130 

Ref:  https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-nccalcsize

### CODE REVIEW

**Comment by Jamminroot** [comment]
Not sure if this is going to be merged, but I'd really like to thank @bufan22 for that :) Fixed the problem I had with windows 11 (beta channel)

**Comment by tenhobi** [comment]
I confirm that this fixes the issue on Windows 11. Can this be merged, please? @bitsdojo 🙏

**Comment by KikiManjaro** [comment]
I had the same problem, this fix everything

**Comment by devtud** [comment]
> I had the same problem, this fix everything

How did you test it? Can you please paste here your dependency? Thanks!

**Comment by KikiManjaro** [comment]
> > I had the same problem, this fix everything
> 
> How did you test it? Can you please paste here your dependency? Thanks!

I've just added :

```
        if (!wparam)
        {
            return 0;
        }
```

At line 260 of `bitsdojo_window_windows/windows/bitsdojo_window.cpp` of my project dependencies

The file is also available in the changes of this MR.

Note: this is just a workaround until this MR is merged

**Comment by bitsdojo** [comment]
Fixed by https://github.com/bitsdojo/bitsdojo_window/commit/9b83939c321caa438da4be598f527f028e0efa5f

**Pull request closed without merging**
